/** Auto-generated by scripts/stamp-version.js — do not edit */
export const BUILD_STAMP: {
  version: string;
  buildId: string;
  forceUpdate: boolean;
  notes: string;
  releasedAt: string;
} = {
  "version": "1.0.1",
  "buildId": "bms74z6pt",
  "forceUpdate": false,
  "notes": "A newer version of Givit is available with the latest features and fixes.",
  "releasedAt": "2026-07-30T06:32:18.882Z"
};
