/**
 * Writes public/version.json and injects BUILD_ID for web deploys.
 * Called before `expo export` so installed PWAs can detect updates.
 */
const fs = require('fs');
const path = require('path');

const root = path.join(__dirname, '..');
const pkg = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8'));
const appJson = JSON.parse(fs.readFileSync(path.join(root, 'app.json'), 'utf8'));

const version = appJson?.expo?.version || pkg.version || '1.0.0';
const buildId =
  process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 12) ||
  process.env.GITHUB_SHA?.slice(0, 12) ||
  `b${Date.now().toString(36)}`;

const forceUpdate = process.env.GIVIT_FORCE_UPDATE === '1';
const notes =
  process.env.GIVIT_UPDATE_NOTES ||
  'A newer version of Givit is available with the latest features and fixes.';

const payload = {
  version,
  buildId,
  forceUpdate,
  notes,
  releasedAt: new Date().toISOString(),
};

const pub = path.join(root, 'public');
if (!fs.existsSync(pub)) fs.mkdirSync(pub, { recursive: true });

fs.writeFileSync(path.join(pub, 'version.json'), JSON.stringify(payload, null, 2) + '\n');

// Also stamp into a tiny JS module the app can import at runtime on web
const stampDir = path.join(root, 'src', 'config');
fs.writeFileSync(
  path.join(stampDir, 'buildStamp.ts'),
  `/** Auto-generated by scripts/stamp-version.js — do not edit */\n` +
    `export const BUILD_STAMP: {\n` +
    `  version: string;\n` +
    `  buildId: string;\n` +
    `  forceUpdate: boolean;\n` +
    `  notes: string;\n` +
    `  releasedAt: string;\n` +
    `} = ${JSON.stringify(payload, null, 2)};\n`,
);

console.log('Stamped version', payload);
